version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    IMAGE_REPO_NAME: "domain-research-agent"
    ECS_CLUSTER_NAME: "domain-research-cluster"
    ECS_SERVICE_NAME: "domain-research-service"
    CONTAINER_NAME: "domain-research-container"

phases:
  pre_build:
    commands:
      - echo "Logging into AWS ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 161313707195.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Connected to ecr"
      - IMAGE_TAG="latest"
      - echo "Using image tag $IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 161313707195.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 161313707195.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Retrieving image digest..."
      - IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_REPO_NAME:$IMAGE_TAG | cut -d '@' -f 2)
      - echo "Image digest: $IMAGE_DIGEST"
      - IMAGE_URI="161313707195.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME@sha256:$IMAGE_DIGEST"
      - printf '{"imageUri":"%s"}' "$IMAGE_URI" > imagedefinitions.json
      - echo "Image update complete!!"

artifacts:
  files:
    - imagedefinitions.json
